update  required controllers for n+1 issue
codeWithHyder/blog-rails pull request #8
Opened 2023-06-26 14:42 UTC by codeWithHyder

n+1

- [ ] Make sure that the N+1 problem is solved when fetching all posts and their comments for a user.
- [ ] Do not use the bullet gem in this exercise - instead analyze the logs as showed in this [article](https://dev.to/junko911/rails-n-1-queries-and-eager-loading-10eh)
- [ ] In your PR description include the screenshots of your app's logs before and after the fix
Before N+1 application:

![image](https://github.com/codeWithHyder/blog-rails/assets/105491212/3d44acd0-9cfd-4686-90b4-a387e90fcd4c)

After N+1 Application:
![image](https://github.com/codeWithHyder/blog-rails/assets/105491212/c60dfe6f-b67c-4990-bcf4-a7c4cf731f6f)

**Integration specs**
Use Capybara to write integration tests for each view in your project.

Think on the flow of things and group the tests of page in a way that makes sense. For example, one test would check for the things in the page and another test for clicking links on it.

User index page:

We can see the username of all other users.
We can see the profile picture for each user.
We can see the number of posts each user has written.
When user is clicked, the page is redirected to that user's show page.
user show page:

We can see the user's profile picture.
We can see the user's username.
We can see the number of posts the user has written.
We can see the user's bio.
We can see the user's first 3 posts.
We can see a button that lets me view all of a user's posts.
When the user's post is clicked, it redirects to that post's show page.
When 'see all posts' is clicked, it redirects to the user's post's index page.
User post index page:

We can see the user's profile picture.
We can see the user's username.
We can see the number of posts the user has written.
We can see a post's title.
We can see some of the post's body.
We can see the first comments on a post.
We can see how many comments a post has.
We can see how many likes a post has.
We can see a section for pagination if there are more posts than fit on the view.
When I click on a post, it redirects me to that post's show page.
Post show page:

We can see the post's title.
We can see who wrote the post.
We can see how many comments it has.
We can see how many likes it has.
We can see the post body.
We can see the username of each commentor.
We can see the comment each commentor left.

![image](https://github.com/codeWithHyder/blog-rails/assets/105491212/ac4e8d92-d7e7-48c5-9530-85fb19d0653a)

2023-06-26 16:29 UTC, julie-ify reviewed
Hi @codeWithHyder and @ZewdieMc,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

* The second reviewer updated only the readme file. Note that this is not a valid contribution to the project. All coding partners need to write actual code in the project.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-06-26 19:54 UTC, DammyShittu requested changes
Hi @codeWithHyder and @ZewdieMc,

## Highlights
✔️ Passing tests

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-26 19:54 UTC, DammyShittu commented on app/controllers/posts_controller.rb
> +    @posts = @user.posts
- [ ] Kindly eliminate N+1 query problem in this post index action.

  ```
  @posts = @user.posts.includes(:comments)
  ```

2023-06-26 19:54 UTC, DammyShittu commented on spec/views/views_integration/post_spec.rb
> +    end
- [ ] You added tests for only posts without adding tests for the user index and show pages. Kindly add integration tests for the user's pages.

  ![image](https://github.com/codeWithHyder/blog-rails/assets/54848363/7651fea6-a965-47c9-924c-1f1397bb792d)

- **[OPTIONAL]** Splitting these tests in two files (post_index_spec.rb and post_show_spec.rb) would help in a better test organization, so I strongly recommend it.

2023-06-27 08:36 UTC, Lucas-Masaba requested changes
# Hello @codeWithHyder and @DammyShittu  👋 , 

Good job so far! 👍 
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost-there](https://media.giphy.com/media/ReyD4OdRiHeLDCRaEP/giphy.gif)

## Highlights 🍾 
- Linter checks passing :heavy_check_mark: 
- Well written PR description :writing_hand: 
- Solved N+1 problems

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions 💭 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Lucas-Masaba in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-27 08:36 UTC, Lucas-Masaba commented on app/models/user.rb
- [ ] When I run your tests I get an error as seen in the screenshot below. This is because of line 18  and 22. Instead of just `post_id:`, I replaced it with `post_id: user_id` and all the tests passed. Please look into it.
![image](https://github.com/codeWithHyder/blog-rails/assets/45460192/8fa5f1b8-bb99-4866-be4f-cf736b9afdf2)

2023-06-27 10:05 UTC, bobb-Rob approved these changes
## STATUS: APPROVED ✔️ 🍾 🍾 🍾 🥳 🥳 🥳 

Hi @codeWithHyder , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://camo.githubusercontent.com/2c67944c14f5c74b9b607df18d73efb0c423dd148b3e10cb75b445a00220332e/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f5061536e555a573145657970756c734f77642f67697068792e676966)

## Highlights
✅ No Linter error
✅ Correct use of Gitflow
✅ Very descriptive Pull Request(PR)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-27 10:12 UTC, merged